# skills_mapping.py

SKILLS_MAPPING = {
    "DSA": 1,
    "System Design": 2,
    "Object-Oriented Programming": 3,
    "Problem Solving": 4,
    "Version Control": 5,
    "SQL Queries": 6,
    "Data Visualisation": 7,
    "Excel Advanced": 8,
    "Statistics and Probability": 9,
    "Python for Data Analysis": 10,
    "Python": 11,
    "Machine Learning": 12,
    "Deep Learning": 13,
    "Generative AI/LLMs": 14,
    "MLops": 15,
    "Cloud": 16,
    "JavaScript": 17,
    "Java Spring Boot": 18,
    "REST / GraphQL APIs": 19,
    "NoSQL": 20,
    "Authentication": 21,
    "Docker": 22,
    "CI/CD": 23,
    "HTML": 24,
    "CSS": 25,
    "TypeScript": 26,
    "React": 27,
    "Angular": 28,
    "State Management": 29,
    "Responsive Design": 30
}